server:
  port: 8083

spring:
  application:
    name: usage-service
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/energydb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

rabbitmq:
  usage:
    queue: energy-data
    exchange: energy-exchange
    routing-key: energy.data
  updates:
    routing-key: energy.update
