server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/energydb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

rabbitmq:
  percentage:
    queue: current-percentage-queue
    exchange: energy-exchange
    routing-key: energy.update
